"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: set SECRET_KEY in .env for production (never commit real secrets).
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dev-only-rotate-for-production",
)

DEBUG = config("DEBUG", default=True, cast=bool)

# * allows any Host header (LAN, tunnels). Django only permits * when DEBUG=True.
_allowed = config("ALLOWED_HOSTS", default="localhost,127.0.0.1,*").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
if not DEBUG:
    ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h != "*"]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
elif DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + ["127.0.0.1", "localhost", "*"]))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lms',
    'storages',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'lms.context_processors.conversion',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/courses/"

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# LMS
LMS_COURSES_PER_PAGE = 12
LMS_DASHBOARD_PER_PAGE = 20
LMS_S3_PRESIGNED_EXPIRY = 300
LMS_VERIFICATION_BASE_URL = ""
LMS_CERTIFICATE_EMAIL_SUBJECT = "Your Certificate"
LMS_OTP_EMAIL_SUBJECT = config("LMS_OTP_EMAIL_SUBJECT", default="Your BThinkX sign-in code")
LMS_DEMO_VIDEO_KEY = "videos/demo-course.mp4"

# AWS S3 (placeholder; set in production)
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_STORAGE_BUCKET_NAME = ""
AWS_S3_REGION_NAME = ""

# S3 Hero Video Configuration
# Option 1: Direct S3 URL (public bucket)
# AWS_S3_HERO_VIDEO_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/hero-video.mp4"

# Option 2: CloudFront CDN URL (recommended for production)
# AWS_CLOUDFRONT_DOMAIN = "d1234567890.cloudfront.net"
# AWS_S3_HERO_VIDEO_URL = f"https://{AWS_CLOUDFRONT_DOMAIN}/hero-video.mp4"

# Option 3: Use presigned URLs (private bucket) - Generate in views.py using services.py
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="app.email_backend.CustomEmailBackend",
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER or "noreply@example.com")
# Absolute site URL for email links (e.g. https://yoursite.com), used when request is unavailable
LMS_PUBLIC_BASE_URL = config("LMS_PUBLIC_BASE_URL", default="").strip().rstrip("/")
LMS_EMAIL_BRAND_NAME = config("LMS_EMAIL_BRAND_NAME", default="BThinkX")
CONTACT_EMAIL_TO = config("CONTACT_EMAIL_TO", default="")
_admin_emails = config("ADMIN_NOTIFICATION_EMAILS", default="").strip()
ADMIN_NOTIFICATION_EMAILS = [
    e.strip() for e in _admin_emails.split(",") if e.strip()
]

# Razorpay Configuration (empty defaults allow runserver without payment keys)
RZP_CLIENT_ID = config("RZP_CLIENT_ID", default="")
RZP_CLIENT_SECRET = config("RZP_CLIENT_SECRET", default="")
RZP_CURRENCY = "INR"

# Single-course pricing (amount in rupees, Razorpay uses paise)
LMS_COURSE_PRICE_INR = 2499
LMS_ORIGINAL_PRICE_INR = 4999  # strikethrough display on landing / course
# Optional MP4 URLs for preview videos (/courses/ banner + course detail sidebar)
LMS_COURSE_PREVIEW_VIDEO_URL = config("LMS_COURSE_PREVIEW_VIDEO_URL", default="").strip()
LMS_COURSES_PAGE_VIDEO_URL = config("LMS_COURSES_PAGE_VIDEO_URL", default="").strip()

# WhatsApp (digits only, country code without +) e.g. 919876543210
LMS_WHATSAPP_NUMBER = config("LMS_WHATSAPP_NUMBER", default="")
LMS_WHATSAPP_MESSAGE = config(
    "LMS_WHATSAPP_MESSAGE",
    default="Hi, I'm interested in the Prompt Engineering course",
)

# Offer countdown (ISO 8601 end datetime, UTC), empty = hide timer
LMS_OFFER_COUNTDOWN_END = config("LMS_OFFER_COUNTDOWN_END", default="")
LMS_LIMITED_SEATS_TEXT = "Only a few seats left at this price. Enroll today."

# Optional PDF URL after lead magnet submit (email automation hook)
LMS_LEAD_MAGNET_PDF_URL = config("LMS_LEAD_MAGNET_PDF_URL", default="")
# Future: POST leads to Zapier/Make, LMS_LEAD_WEBHOOK_URL = config(...)

# Scarcity: "seats left" = LMS_TOTAL_SEATS − enrollments (0 = hide)
LMS_TOTAL_SEATS = config("LMS_TOTAL_SEATS", default=0, cast=int)

# Referral: discount % when ?ref=VALID_CODE at checkout (0 = disable)
LMS_REFERRAL_DISCOUNT_PERCENT = config("LMS_REFERRAL_DISCOUNT_PERCENT", default=0, cast=int)

# Post-purchase upsell modal (empty title = disabled)
LMS_POST_PURCHASE_UPSELL_TITLE = config("LMS_POST_PURCHASE_UPSELL_TITLE", default="")
LMS_POST_PURCHASE_UPSELL_BODY = config(
    "LMS_POST_PURCHASE_UPSELL_BODY",
    default="Add the Freelance AI Toolkit, templates, contracts, and proposal prompts.",
)
LMS_POST_PURCHASE_UPSELL_URL = config("LMS_POST_PURCHASE_UPSELL_URL", default="/courses/")
LMS_POST_PURCHASE_UPSELL_CTA = config("LMS_POST_PURCHASE_UPSELL_CTA", default="View add-on")

# Lead follow-up emails (set False to skip in dev)
LMS_FOLLOWUP_SEND_EMAIL = config("LMS_FOLLOWUP_SEND_EMAIL", default=True, cast=bool)

# Identity-based copy (hero, CTAs, headings)
LMS_IDENTITY_LABEL = config("LMS_IDENTITY_LABEL", default="AI Freelancer")

# Live activity toasts (enrollment / lead / certificate, see ActivityEvent)
LMS_LIVE_ACTIVITY_ENABLED = config("LMS_LIVE_ACTIVITY_ENABLED", default=True, cast=bool)
LMS_LIVE_ACTIVITY_FALLBACK = config(
    "LMS_LIVE_ACTIVITY_FALLBACK",
    default=False,
    cast=bool,
)  # generic lines if DB empty (off by default, no fake names)

# Mentor CTA: Calendly wins over WhatsApp if both set
LMS_MENTOR_CALENDLY_URL = config("LMS_MENTOR_CALENDLY_URL", default="")
LMS_MENTOR_WHATSAPP_MESSAGE = config(
    "LMS_MENTOR_WHATSAPP_MESSAGE",
    default="Hi, I'd like to speak with a mentor before enrolling.",
)
LMS_MENTOR_CTA_CALENDLY = config("LMS_MENTOR_CTA_CALENDLY", default="Book a call")
LMS_MENTOR_CTA_WHATSAPP = config("LMS_MENTOR_CTA_WHATSAPP", default="Talk to mentor")


# AWS S3 Storage configuration (media only; static files remain local)
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME")

    # Optional: tag all S3 objects by client / project (e.g. kids-shelf)
    AWS_S3_CLIENT_TAG = config("AWS_S3_CLIENT_TAG", default=None)

    # Correct S3 custom domain with region
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    # S3 Configuration (No ACLs - rely on bucket policy)
    # Bucket has "BucketOwnerEnforced" which disables ACLs
    base_s3_object_params = {
        'CacheControl': 'max-age=86400',
    }
    # If a client tag is configured, add it as an S3 object tag
    # This results in Tagging="Client=kids-shelf" on every uploaded object
    if AWS_S3_CLIENT_TAG:
        base_s3_object_params['Tagging'] = f'Client={AWS_S3_CLIENT_TAG}'

    AWS_S3_OBJECT_PARAMETERS = base_s3_object_params
    AWS_DEFAULT_ACL = None  # Don't use ACLs, bucket policy handles public access
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False

    # Django 4.2+ STORAGES setting
    # Only media files go to S3; static files are always served locally
    STORAGES = {
        "default": {
            # Use django-storages S3 backend for media files
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    # Public base URL for media files in S3:
    # files will be stored under: kids-shelf/media/<upload_to>/<filename>
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/kids-shelf/media/"
else:
    # Local file storage for everything
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"

# Session / cookie hardening in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
if not DEBUG:
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# Logging (payments, OTP, leads)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "lms.payments": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "lms.otp": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "lms.leads": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
